namespace Common
{
	// 21 이상부터 시작해야 한다!!!
	enum PACKET_ID : short
	{

		ROOM_ENTER_REQ = 21, //선택 방 입장요청
		ROOM_ENTER_NOW_REQ = 22, //바로 입장
		ROOM_ENTER_RES = 23,
		
		ROOM_ENTER_USER_LIST_REQ = 25,
		ROOM_ENTER_USER_LIST_RES = 26,
		ROOM_ENTER_USER_NTF = 27,

		ROOM_LEAVE_REQ = 31,
		ROOM_LEAVE_RES = 32,
		ROOM_LEAVE_USER_NTF = 33,

		CHANNEL_JOIN_REQ = 41,
		CHANNEL_JOIN_RES = 42,
		CHANNEL_JOIN_NTF = 43,

		CHANNEL_LEAVE_REQ = 51,
		CHANNEL_LEAVE_RES = 52,
		CHANNEL_LEAVE_USER_NTF = 53,


		GAME_BET_REQ = 101,
		GAME_BET_RES = 102,
		GAME_BET_NTF = 103,

		GAME_PLAY_REQ = 111,
		GAME_PLAY_RES = 112,
		GAME_PLAY_NTF = 113,

		GAME_EMOTION_REQ = 121,
		GAME_EMOTION_RES = 122,
		GAME_EMOTION_NTF = 123,
		
	};
}